name: Publish New Version

on:
    release:
        types: [created]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn
            - run: yarn test
            - run: yarn build
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}